### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by crymscom** [SRGSSR/srgletterbox-apple#167] opened 2019-04-02 12:53 UTC
Hello, we are evaluating the feasibility of developing an app for Apple TV that integrates the Letterbox frameworks.

Could you please tell us if is supported or if is planned for the future?

**Comment by defagos** [comment] 2019-04-02 17:10
Hi! Sorry, at the moment there is no work going on in making our Letterbox ecosystem compatible with tvOS. This is of course something we would like to provide (in fact we already hacked some SRG Media Player-based tvOS app prototype in the past), but this requires work for which we sadly have no dedicated time at the moment.

**Comment by defagos** [comment] 2019-04-10 18:24
For information, we have started work to add tvOS support to [SRG Media Player](https://github.com/SRGSSR/srgmediaplayer-ios/tree/feature/tvOS).

This looks very promising, but of course requires further work. SRG Letterbox support is still far away, though, as we have to update several more frameworks to make it possible.

This work is done on our spare time, though, so we cannot promise you when tvOS support will be delivered in a stable form.

**Comment by crymscom** [comment] 2019-04-11 07:31
Hello, thank you for your update.

We have also worked to adapt the frameworks to support tvOS and at the moment I believe we have reached our goal.

We have removed all reference to not supported features on Apple TV as CoreMotion, PictureInPicture, ... and recompiled these frameworks:
- srgletterbox-ios
- srgmediaplayer-ios
- srganalytics-ios
- srgdataprovider-ios

We've developed a demo app that need more tests, but the livestreams are played correctly with the analytics integration. 

We have forked your repositories to ours and added a new branch to work on.
If you need I can share my work with you.

Let me know if you're interested.

**Comment by defagos** [comment] 2019-04-11 08:36
Hi!

We are interested in seing the result, especially what it looks like in Letterbox, so that we can have a better understanding / estimate of the required UI work we might have to do. Thanks for the proposal!

**Comment by crymscom** [comment] 2019-04-11 09:31
Ok so I will push my branch to your repository under feature/tvOS-cryms.
It's ok for you?

I don't know if I've write permission, could you check?

**Comment by defagos** [comment] 2019-04-11 12:01
You don't have write permissions on our repository (since you are not part of the core player development team), so your branch cannot be pushed there I am afraid.

I am not sure if you have noticed, but Letterbox is now entirely open source. So if there is nothing preventing you from doing it, couldn't you make your fork public as well and give us the link? Thanks!

**Comment by crymscom** [comment] 2019-04-11 13:22
Ok no problem.

I've re-created the fork directly on GitHub so you can reach it more easily and I've sent to you the relative pull requests for thesse projects:

- srgletterbox-ios
- srgmediaplayer-ios
- srganalytics-ios
- srgdataprovider-ios

As I wrote in the pull request description:

> Due to time limits I didn't handled tvOS as a second target but I simply adapted the project removing or changing the conflicting parts of the code.
> 
> The best thing would be to create a new target and manage code blocks using #if TARGET_OS_IOS or #if TARGET_OS_TV as you made in your tvOS branch of SRGMediaPlayer

So I'me sorry if my solution it's not the cleanest one.

**Comment by defagos** [comment] 2019-04-12 07:23
Thank you very much! I'll try to have a look at it in the upcoming days.

Don't be sorry if your solution is not clean, I think this is not your goal here. We'll hopefully able to deliver full tvOS support in a not so distant future anyway.

**Comment by defagos** [comment] 2019-09-20 09:11
tvOS support is being added at the moment. Here is a checklist of what still needs to be done:

- [ ] Make the project compile and run for tvOS in a basic way.
- [ ] Remove Hockey App (will need to be updated anyway), for which we only link the iOS version at the moment. This will be restored later, probably with AppCenter.
- [ ] For tvOS, implement Letterbox view controller using `AVPlayerViewController`.
- [ ] Implement metadata and segments in `AVPlayerViewController` info panel.
- [ ] Implement error overlay.
- [ ] Implement availability overlay.
- [ ] Implement continuous playback with native `AVPlayerViewController` support.
- [ ] Display thumbnail in background for audio.

**Comment by defagos** [comment] 2019-09-23 19:01
Issues with content proposal implementation:

- UI is not dismissed if button is tapped while being displayed.
- If continuing when another content, sometimes the video retains the top left position (breaking conflicting constraints).

Issues remaining with metadata implementation:

- Couleur 3 logo is not displayed.

**Comment by defagos** [comment] 2019-09-23 19:19
The two content proposal issues above have been fixed by setting the content proposal time to indefinite. I truly don't understand why this works, though.

**Comment by defagos** [comment] 2019-10-09 14:20
The Apple TV should respond to the user in a standard way [according to the HIG](https://developer.apple.com/design/human-interface-guidelines/tvos/remote-and-controllers/remote/). Yet the standard behavior of the Menu and Home somehow remains a mystery to me, in particular the following interactions:

- Single pressing the Menu button.
- Long pressing the Menu button.
- Single pressing the Home button.

To identify a common standard behavior, I had a look at several tvOS applications:

### Apple apps

- tv
   - Single Menu press:
   - Long Menu press:
   - Single Home press:
- movies iTunes
   - Single Menu press:
   - Long Menu press:
   - Single Home press:
- Photos
   - Single Menu press:
   - Long Menu press:
   - Single Home press:
- Apple Events
   - Single Menu press:
   - Long Menu press:
   - Single Home press:
- WWDC
   - Single Menu press:
   - Long Menu press:
   - Single Home press:

### Third-party apps

- Youtube
   - Single Menu press:
   - Long Menu press:
   - Single Home press:
- Arte
   - Single Menu press:
   - Long Menu press:
   - Single Home press:
- TED
   - Single Menu press:
   - Long Menu press:
   - Single Home press:
- Vimeo
   - Single Menu press:
   - Long Menu press:
   - Single Home press:
- Netflix
   - Single Menu press:
   - Long Menu press:
   - Single Home press:

Whether we should then implement a standard behavior can either be done at the Letterbox level or at the SRG Media Player level.

**Comment by defagos** [comment] 2019-10-10 06:05
The 360° _leak_ described above is not really a leak, merely an incorrect behavior we have on tvOS. I recommend we implement the following approach to ensure consistency with our iOS implementation and usual tvOS player behavior:

- `SRGMediaPlayerView` should provide background behaviors as for iOS (of course, the lock device constant is iOS-specific only), affecting video playback.
- Playback should not automatically resume when the app resumes, as on iOS.
- `SRGMediaPlayerViewController` should automatically resume playback, though (see previous comment).

**Comment by defagos** [comment] 2019-10-10 17:32
@crymscom We have made significant progress on Letterbox for tvOS. Most of the work will now be done within a few days. Before we officially publish a Letterbox release with tvOS support, we still need to receive dedicated TagCommander SDKs, and we would like to validate that the work we have done is actually compatible with AppStore validation rules (this should be the case since we didn't do anything prohibited, but you never know).

For this to succeed your assistance would be greatly appreciated. We discussed a strategy with @pyby , and though the details might slightly change, here is a first proposal I would like to share with you. We can discuss and refine it further with your input, of course, and you are perfectly free to refuse the overall idea or to propose something entirely different:

- Once we have TagCommander tvOS SDKs, we finalize our tvOS support, ensure everything works according to our quality standards, and deliver a Letterbox release candidate for iOS and tvOS.
- We either integrate this Letterbox RC version in your RSI Apple TV application and submit the result to you as a pull request (this will be very simple to integrate), or you do it if you have the time and want to do it. As a result, your app will get new functionalities for free (playback controls, DVR support on streams supporting it, automatic thumbnail display for videos and audios, analytics, metadata display).
- You submit this new application to Apple. If approved we will deliver a final official Letterbox release, with which you can submit a new binary for review and release, otherwise we will make the necessary adjustments until you can successfully publish the app.

If this seems sound to you or if you have feedback, feel free to contact us. You might of course want to talk with RSI as well to plan things a bit ahead. If you want to discuss it directly over the phone, we of course stay at your disposal.

Thanks in advance for your help!

**Comment by defagos** [comment] 2019-10-24 08:24
The native content proposal mechanism cannot sadly be used to implement continuous playback. The issue is that the content proposal internal implementation changes the player state to directly resume content at the beginning (see [official documentation](https://developer.apple.com/documentation/avkit/avcontentproposalviewcontroller/1650973-dismisscontentproposalforaction?language=objc)). 

Since we might want the next item in a playlist to resume at a precise location, not at the beginning (e.g. resume playback, next content is a segment from a full-length), the player changes conflict with ours and in most cases force the player to restart at the beginning.

For this reason, we need to display our own user interface for continuous playback.

**Comment by pyby** [comment] 2019-11-23 22:45
On tvOS 12.4, we should test again:
- Dark mode support (I've a white list when dark mode on with Nightly build 14).
- A black screen when a geo blocked content opened (after less than 1 second displaying the error).

**Comment by defagos** [comment] 2019-11-28 16:01
There is still a minor issue with the tvOS Letterbox view controller: If playback is paused, then resumed, and the player closed afterwards (even after a while), audio playback continues in the background for a little while.

**Comment by defagos** [comment] 2019-11-29 09:56
The issue discussed above has been fixed on `feature/early-deallocation` branches, both on SRG Media Player and SRG Letterbox repositories. These are ready for code review.

**Comment by defagos** [comment] 2019-11-29 18:53
Another issue was found: There should be automatic page view tracking for Letterbox view controller on tvOS.

This is pretty much standard and after giving it some thought I recommend we implement automatic `SRGMediaPlayerViewController` tracking in SRG Analytics. This way the behavior is inherited by Letterbox automatically, as its tvOS view controller embeds a media player view controller as child.

The simplest approach is to conform to `SRGAnalyticsViewTracking`, and to use a fixed page title (I simply propose `player`). I doubt there is a need for customization, and this avoids unnecessary complicated logic, while ensuring measurements are made according to our standards when the view appear for the first time.

An implementation proposal is available on SRG Analytics `feature/tvOS-player-view-event` branch.

**Comment by pyby** [comment] 2019-12-03 09:50
> To fix the issue, it should suffice to call `-reset` on the controller when the view disappears

For now, we don't have a feature request to keep the controller alive when closing the `SRGLetterboxViewController` but on `SRGMediaPlayerViewController`, we must not reset it if it disappears because Picture in Picture started.

**Comment by pyby** [comment] 2019-12-09 21:41
- [ ] We should fix the focus on tvOS demo after a long asynchronous request. We expect to have an item (first table view item or a button) to be focused, and avoid an application exit with the menu button.

**Comment by pyby** [comment] 2019-12-14 11:02
@svenduvoisin reported an UX experience issue with Letterbox demo:

- Open the tvOS demo application.
- Open the first media in the list: playback starts without control bar at the bottom.

With the Apple remote, click (click and hold) on the right side to seek forward.
- Expected behaviour: the control bar at the bottom is displayed and it seeks forward.
- Current behaviour: Do nothing.

After displaying one time the control bar, the "native default" behaviour is as expected.

Tested on 2 AppleTV with tvOS13.x at the office:
- Works on Apple TV+, also in SRG Media Player demo with the `System Player` or `SRGMediaPlayer`.
- Does not work on a third Apple TV  with tvOS13.x on my side.

**Comment by defagos** [comment] 2019-12-14 13:29
The user interaction issue has been fixed. It was due to `userInteractionEnabled` being toggled on `AVPlayerViewController` view, which seems not to be supported well enough.

The price to pay is that the UI can be toggled in situations where the UI is not so useful (error, countdown, end of playback), but this is probably the price to pay for having a good UX, and is not really a problem from a usability point of view.

**Comment by defagos** [comment] 2019-12-17 18:45
🍾

**Closed** 2019-12-17 18:56 UTC
Labels: enhancement
